### ISSUE TITLE
Running example launch file

### ISSUE THREAD

**Issue by bvibhav** [patrykcieslak/stonefish_ros#16]
I am trying to launch the the files within `cola2_stonefish`, but encountering an error:
`resource not found: cola2_lib_ros`. 

Where can find the package to get this lib?

**Comment by patrykcieslak** [comment]
You have to go to the repo of iquarobotics on bitbucket. It is a ros package but you will also need a non-ROS library called cola2_lib. All cola2 stuff is under iquarobotics.
