### ISSUE TITLE
Split out Girona500 simulations

### ISSUE THREAD

**Issue by nilsbore** [patrykcieslak/stonefish_ros#7]
Would it be possible to split out the Girona500 simulations into a package that would depend on this? As far as I can tell, that would get rid of all of the dependencies for this package except for cola2_lib. This would make it significantly easier for any outside users that want to use it with just their own AUV, while still allowing them to try the Girona500 and Sparus AUVs uising the other new package.

**Comment by nilsbore** [comment]
The PR https://github.com/patrykcieslak/stonefish_ros/pull/8 does this, together with some further simplifications.

**Comment by patrykcieslak** [comment]
I did it and got rid of the cola2_ros_lib also. Now the examples are in the 'stonefish_cirs' repository.
I am not a fan of including libraries as submodules in a ROS package. I always prefered to install them myself separately.
